module.exports = [
    { value: 'Affenpinscher', label: 'Affenpinscher' },
    { value: 'Afghan Hound', label: 'Afghan Hound' },
    { value: 'Airedale Terrier', label: 'Airedale Terrier' },
    { value: 'Akita', label: 'Akita' },
    { value: 'Alaskan Malamute', label: 'Alaskan Malamute' },
    { value: 'American Cocker Spaniel',
      label: 'American Cocker Spaniel' },
    { value: 'American Eskimo Dog', label: 'American Eskimo Dog' },
    { value: 'American Foxhound', label: 'American Foxhound' },
    { value: 'American Staffordshire Terrier',
      label: 'American Staffordshire Terrier' },
    { value: 'American Water Spaniel',
      label: 'American Water Spaniel' },
    { value: 'Anatolian Shepherd', label: 'Anatolian Shepherd' },
    { value: 'Australian Cattle Dog',
      label: 'Australian Cattle Dog' },
    { value: 'Australian Shepherd', label: 'Australian Shepherd' },
    { value: 'Australian Terrier', label: 'Australian Terrier' },
    { value: 'Basenji', label: 'Basenji' },
    { value: 'Basset Hound', label: 'Basset Hound' },
    { value: 'Beagle', label: 'Beagle' },
    { value: 'Bearded Collie', label: 'Bearded Collie' },
    { value: 'Beauceron', label: 'Beauceron' },
    { value: 'Bedlington Terrier', label: 'Bedlington Terrier' },
    { value: 'Belgian Malinois', label: 'Belgian Malinois' },
    { value: 'Belgian Sheepdog', label: 'Belgian Sheepdog' },
    { value: 'Belgian Tervuren', label: 'Belgian Tervuren' },
    { value: 'Bernese Mountain Dog', label: 'Bernese Mountain Dog' },
    { value: 'Bichon Frise', label: 'Bichon Frise' },
    { value: 'Black and Tan Coonhound',
      label: 'Black and Tan Coonhound' },
    { value: 'Black Russian Terrier',
      label: 'Black Russian Terrier' },
    { value: 'Bloodhound', label: 'Bloodhound' },
    { value: 'Border Collie', label: 'Border Collie' },
    { value: 'Border Terrier', label: 'Border Terrier' },
    { value: 'Borzoi', label: 'Borzoi' },
    { value: 'Boston Terrier', label: 'Boston Terrier' },
    { value: 'Bouvier des Flandres', label: 'Bouvier des Flandres' },
    { value: 'Boxer', label: 'Boxer' },
    { value: 'Briard', label: 'Briard' },
    { value: 'Brittany', label: 'Brittany' },
    { value: 'Brussels Griffon', label: 'Brussels Griffon' },
    { value: 'Bull Terrier', label: 'Bull Terrier' },
    { value: 'Bulldog', label: 'Bulldog' },
    { value: 'Bullmastiff', label: 'Bullmastiff' },
    { value: 'Cairn Terrier', label: 'Cairn Terrier' },
    { value: 'Canaan Dog', label: 'Canaan Dog' },
    { value: 'Cardigan Welsh Corgi', label: 'Cardigan Welsh Corgi' },
    { value: 'Cavalier King Charles Spaniel',
      label: 'Cavalier King Charles Spaniel' },
    { value: 'Chesapeake Bay Retriever',
      label: 'Chesapeake Bay Retriever' },
    { value: 'Chihuahua', label: 'Chihuahua' },
    { value: 'Chinese Crested Dog', label: 'Chinese Crested Dog' },
    { value: 'Chinese Shar-Pei', label: 'Chinese Shar-Pei' },
    { value: 'Chow Chow', label: 'Chow Chow' },
    { value: 'Clumber Spaniel', label: 'Clumber Spaniel' },
    { value: 'Collie', label: 'Collie' },
    { value: 'Curly-Coated Retriever',
      label: 'Curly-Coated Retriever' },
    { value: 'Dachshund', label: 'Dachshund' },
    { value: 'Dalmatian', label: 'Dalmatian' },
    { value: 'Dandie Dinmont Terrier',
      label: 'Dandie Dinmont Terrier' },
    { value: 'Doberman Pinscher', label: 'Doberman Pinscher' },
    { value: 'English Cocker Spaniel',
      label: 'English Cocker Spaniel' },
    { value: 'English Foxhound', label: 'English Foxhound' },
    { value: 'English Setter', label: 'English Setter' },
    { value: 'English Springer Spaniel',
      label: 'English Springer Spaniel' },
    { value: 'English Toy Spaniel', label: 'English Toy Spaniel' },
    { value: 'Field Spaniel', label: 'Field Spaniel' },
    { value: 'Finnish Spitz', label: 'Finnish Spitz' },
    { value: 'Flat-Coated Retriever',
      label: 'Flat-Coated Retriever' },
    { value: 'French Bulldog', label: 'French Bulldog' },
    { value: 'German Pinscher', label: 'German Pinscher' },
    { value: 'German Shepherd Dog', label: 'German Shepherd Dog' },
    { value: 'German Shorthaired Pointer',
      label: 'German Shorthaired Pointer' },
    { value: 'German Wirehaired Pointer',
      label: 'German Wirehaired Pointer' },
    { value: 'Giant Schnauzer', label: 'Giant Schnauzer' },
    { value: 'Glen of Imaal Terrier',
      label: 'Glen of Imaal Terrier' },
    { value: 'Golden Retriever', label: 'Golden Retriever' },
    { value: 'Gordon Setter', label: 'Gordon Setter' },
    { value: 'Great Dane', label: 'Great Dane' },
    { value: 'Great Pyrenees', label: 'Great Pyrenees' },
    { value: 'Greater Swiss Mountain Dog',
      label: 'Greater Swiss Mountain Dog' },
    { value: 'Greyhound', label: 'Greyhound' },
    { value: 'Harrier', label: 'Harrier' },
    { value: 'Havanese', label: 'Havanese' },
    { value: 'Ibizan Hound', label: 'Ibizan Hound' },
    { value: 'Irish Setter', label: 'Irish Setter' },
    { value: 'Irish Terrier', label: 'Irish Terrier' },
    { value: 'Irish Water Spaniel', label: 'Irish Water Spaniel' },
    { value: 'Irish Wolfhound', label: 'Irish Wolfhound' },
    { value: 'Italian Greyhound', label: 'Italian Greyhound' },
    { value: 'Japanese Chin', label: 'Japanese Chin' },
    { value: 'Keeshond', label: 'Keeshond' },
    { value: 'Kerry Blue Terrier', label: 'Kerry Blue Terrier' },
    { value: 'Komondor', label: 'Komondor' },
    { value: 'Kuvasz', label: 'Kuvasz' },
    { value: 'Labrador Retriever', label: 'Labrador Retriever' },
    { value: 'Lakeland Terrier', label: 'Lakeland Terrier' },
    { value: 'Lhasa Apso', label: 'Lhasa Apso' },
    { value: 'Lowchen', label: 'Lowchen' },
    { value: 'Maltese', label: 'Maltese' },
    { value: 'Manchester Terrier', label: 'Manchester Terrier' },
    { value: 'Mastiff', label: 'Mastiff' },
    { value: 'Marvelous Mystery Mutt',
      label: 'Marvelous Mystery Mutt' },
    { value: 'Miniature Bull Terrier',
      label: 'Miniature Bull Terrier' },
    { value: 'Miniature Pinscher', label: 'Miniature Pinscher' },
    { value: 'Miniature Schnauzer', label: 'Miniature Schnauzer' },
    { value: 'Neapolitan Mastiff', label: 'Neapolitan Mastiff' },
    { value: 'Newfoundland', label: 'Newfoundland' },
    { value: 'Norfolk Terrier', label: 'Norfolk Terrier' },
    { value: 'Norwegian Elkhound', label: 'Norwegian Elkhound' },
    { value: 'Norwich Terrier', label: 'Norwich Terrier' },
    { value: 'Nova Scotia Duck Tolling Retriever',
      label: 'Nova Scotia Duck Tolling Retriever' },
    { value: 'Old English Sheepdog', label: 'Old English Sheepdog' },
    { value: 'Otterhound', label: 'Otterhound' },
    { value: 'Papillon', label: 'Papillon' },
    { value: 'Parson Russell Terrier',
      label: 'Parson Russell Terrier' },
    { value: 'Pekingese', label: 'Pekingese' },
    { value: 'Pembroke Welsh Corgi', label: 'Pembroke Welsh Corgi' },
    { value: 'Petit Basset Griffon Vendeen',
      label: 'Petit Basset Griffon Vendeen' },
    { value: 'Pharaoh Hound', label: 'Pharaoh Hound' },
    { value: 'Plott', label: 'Plott' },
    { value: 'Pointer', label: 'Pointer' },
    { value: 'Polish Lowland Sheepdog',
      label: 'Polish Lowland Sheepdog' },
    { value: 'Pomeranian', label: 'Pomeranian' },
    { value: 'Poodle', label: 'Poodle' },
    { value: 'Portuguese Water Dog', label: 'Portuguese Water Dog' },
    { value: 'Pug', label: 'Pug' },
    { value: 'Puli', label: 'Puli' },
    { value: 'Redbone Coonhound', label: 'Redbone Coonhound' },
    { value: 'Rhodesian Ridgeback', label: 'Rhodesian Ridgeback' },
    { value: 'Rottweiler', label: 'Rottweiler' },
    { value: 'Saint Bernard', label: 'Saint Bernard' },
    { value: 'Saluki (or Gazelle Hound)',
      label: 'Saluki (or Gazelle Hound)' },
    { value: 'Samoyed', label: 'Samoyed' },
    { value: 'Schipperke', label: 'Schipperke' },
    { value: 'Scottish Deerhound', label: 'Scottish Deerhound' },
    { value: 'Scottish Terrier', label: 'Scottish Terrier' },
    { value: 'Sealyham Terrier', label: 'Sealyham Terrier' },
    { value: 'Shetland Sheepdog', label: 'Shetland Sheepdog' },
    { value: 'Shiba Inu', label: 'Shiba Inu' },
    { value: 'Shih Tzu', label: 'Shih Tzu' },
    { value: 'Siberian Husky', label: 'Siberian Husky' },
    { value: 'Silky Terrier', label: 'Silky Terrier' },
    { value: 'Skye Terrier', label: 'Skye Terrier' },
    { value: 'Smooth Fox Terrier', label: 'Smooth Fox Terrier' },
    { value: 'Soft Coated Wheaten Terrier',
      label: 'Soft Coated Wheaten Terrier' },
    { value: 'Spinone Italiano', label: 'Spinone Italiano' },
    { value: 'Staffordshire Bull Terrier',
      label: 'Staffordshire Bull Terrier' },
    { value: 'Standard Schnauzer', label: 'Standard Schnauzer' },
    { value: 'Super Rare Breed', label: 'Super Rare Breed' },
    { value: 'Sussex Spaniel', label: 'Sussex Spaniel' },
    { value: 'Tibetan Mastiff', label: 'Tibetan Mastiff' },
    { value: 'Tibetan Spaniel', label: 'Tibetan Spaniel' },
    { value: 'Tibetan Terrier', label: 'Tibetan Terrier' },
    { value: 'Toy Fox Terrier', label: 'Toy Fox Terrier' },
    { value: 'Vizsla', label: 'Vizsla' },
    { value: 'Weimaraner', label: 'Weimaraner' },
    { value: 'Welsh Springer Spaniel',
      label: 'Welsh Springer Spaniel' },
    { value: 'Welsh Terrier', label: 'Welsh Terrier' },
    { value: 'West Highland White Terrier',
      label: 'West Highland White Terrier' },
    { value: 'Whippet', label: 'Whippet' },
    { value: 'Wire Fox Terrier', label: 'Wire Fox Terrier' },
    { value: 'Wirehaired Pointing Griffon',
      label: 'Wirehaired Pointing Griffon' },
    { value: 'Yorkshire Terrier', label: 'Yorkshire Terrier' }
]
