const breeds = [
    {label:'Affenpinscher',value:'Affenpinscher'},
    {label:'Affenpoo',value:'Affenpoo'},
    {label:'Afghan Hound',value:'Afghan Hound'},
    {label:'Afghan Retriever',value:'Afghan Retriever'},
    {label:'Airedale Terrier',value:'Airedale Terrier'},
    {label:'Akita',value:'Akita'},
    {label:'Alaskan Klee Kai',value:'Alaskan Klee Kai'},
    {label:'Alaskan Malamute',value:'Alaskan Malamute'},
    {label:'Alaskan Noble Companion Dog',value:'Alaskan Noble Companion Dog'},
    {label:'American Bulldog',value:'American Bulldog'},
    {label:'American English Coonhound',value:'American English Coonhound'},
    {label:'American Eskimo Dog',value:'American Eskimo Dog'},
    {label:'American Foxhound',value:'American Foxhound'},
    {label:'American Labrador Retriever',value:'American Labrador Retriever'},
    {label:'American Mastiff',value:'American Mastiff'},
    {label:'American Pit Bull Terrier',value:'American Pit Bull Terrier'},
    {label:'American Staffordshire Terrier',value:'American Staffordshire Terrier'},
    {label:'American Water Spaniel',value:'American Water Spaniel'},
    {label:'Anatolian Shepherd',value:'Anatolian Shepherd'},
    {label:'Aussiedoodle',value:'Aussiedoodle'},
    {label:'Australian Cattle Dog',value:'Australian Cattle Dog'},
    {label:'Australian Kelpie',value:'Australian Kelpie'},
    {label:'Australian Shepherd',value:'Australian Shepherd'},
    {label:'Australian Terrier',value:'Australian Terrier'},
    {label:'Azawakh',value:'Azawakh'},
    {label:'Bagle Hound',value:'Bagle Hound'},
    {label:'Basenji',value:'Basenji'},
    {label:'Bassador',value:'Bassador'},
    {label:'Basset Hound',value:'Basset Hound'},
    {label:'Bassetoodle',value:'Bassetoodle'},
    {label:'Beagle',value:'Beagle'},
    {label:'Bearded Collie',value:'Bearded Collie'},
    {label:'Beauceron',value:'Beauceron'},
    {label:'Bedlington Terrier',value:'Bedlington Terrier'},
    {label:'Belgian Malinois',value:'Belgian Malinois'},
    {label:'Belgian Sheepdog',value:'Belgian Sheepdog'},
    {label:'Belgian Shepherd Malinois',value:'Belgian Shepherd Malinois'},
    {label:'Belgian Tervuren',value:'Belgian Tervuren'},
    {label:'Bergamasco',value:'Bergamasco'},
    {label:'Berger Picard',value:'Berger Picard'},
    {label:'Bernedoodle',value:'Bernedoodle'},
    {label:'Bernese Mountain Dog',value:'Bernese Mountain Dog'},
    {label:'Bichon Frise',value:'Bichon Frise'},
    {label:'Bichon Yorkie',value:'Bichon Yorkie'},
    {label:'Bichpoo',value:'Bichpoo'},
    {label:'Black and Tan Coonhound',value:'Black and Tan Coonhound'},
    {label:'Black Russian Terrier',value:'Black Russian Terrier'},
    {label:'Blackmouth Cur',value:'Blackmouth Cur'},
    {label:'Bloodhound',value:'Bloodhound'},
    {label:'Bluetick Coonhound',value:'Bluetick Coonhound'},
    {label:'Bo Chi',value:'Bo Chi'},
    {label:'Boerboel',value:'Boerboel'},
    {label:'Bolognese',value:'Bolognese'},
    {label:'Boodle',value:'Boodle'},
    {label:'Border Terrier',value:'Border Terrier'},
    {label:'Borkie',value:'Borkie'},
    {label:'Borzoi',value:'Borzoi'},
    {label:'Boston Terrier',value:'Boston Terrier'},
    {label:'Bouvier des Flandres',value:'Bouvier des Flandres'},
    {label:'Boxador',value:'Boxador'},
    {label:'Boxer',value:'Boxer'},
    {label:'Boxerdoodle',value:'Boxerdoodle'},
    {label:'Boxerman',value:'Boxerman'},
    {label:'Boykin Spaniel',value:'Boykin Spaniel'},
    {label:'Bracco Italiano',value:'Bracco Italiano'},
    {label:'bRat (Boston and Rat Terrier)',value:'bRat (Boston and Rat Terrier)'},
    {label:'Brazilian Mastiff',value:'Brazilian Mastiff'},
    {label:'Briard',value:'Briard'},
    {label:'Brittany',value:'Brittany'},
    {label:'Brussels Griffon',value:'Brussels Griffon'},
    {label:'Bugg',value:'Bugg'},
    {label:'Bull Terrier',value:'Bull Terrier'},
    {label:'Bullboxer',value:'Bullboxer'},
    {label:'Bulldog',value:'Bulldog'},
    {label:'Bullmastiff',value:'Bullmastiff'},
    {label:'Cadoodle',value:'Cadoodle'},
    {label:'Cairn Terrier',value:'Cairn Terrier'},
    {label:'Canaan Dog',value:'Canaan Dog'},
    {label:'Cane Corso',value:'Cane Corso'},
    {label:'Cardigan Welsh Corgi',value:'Cardigan Welsh Corgi'},
    {label:'Carolina Dog',value:'Carolina Dog'},
    {label:'Catahoula Leopard Dog',value:'Catahoula Leopard Dog'},
    {label:'Caucasian Ovcharka',value:'Caucasian Ovcharka'},
    {label:'Cavachon',value:'Cavachon'},
    {label:'Cavalier King Charles Spaniel',value:'Cavalier King Charles Spaniel'},
    {label:'Cavanese',value:'Cavanese'},
    {label:'Cavapoo',value:'Cavapoo'},
    
    {label:'Cavoodle'},
    {label:'Cesky Terrier'},
    {label:'Chabrador'},
    {label:'Chesapeake Bay Retriever'},
    {label:'Chinese Crested'},
    {label:'Chinese Shar-Pei'},
    {label:'Chion'},
    {label:'Chipoo'},
    {label:'Chiweenie'},
    {label:'Chorkie'},
    {label:'Chow Chow'},
    {label:'Chow Hound'},
    {label:'Chug'},
    {label:"Cirneco dell'Etna"},
    {label:'Clumber Spaniel'},
    {label:'Cockalier'},
    {label:'Cockapoo'},
    {label:'Cocker Spaniel'},
    {label:'Cocker Westie'},
    {label:'Collie'},
    {label:'Corgiador'},
    {label:'Coton de Tuléar'},
    {label:'Curly-Coated Retriever'},
    {label:'Czechoslovakian Wolfdog'},
    {label:'Dalmatian'},
    {label:'Dandie Dinmont Terrier'},
    {label:'Doberman Pinscher'},
    {label:'Dogo Argentino'},
    {label:'Dogue de Bordeaux'},
    {label:'Dorkie'},
    {label:'Doxiepoo'},
    {label:'Doxle'},
    {label:'Dutch Shepherd'},
    {label:'English Bull Boxer'},
    {label:'English Cocker Spaniel'},
    {label:'English Foxhound'},
    {label:'English Labrador Retriever'},
    {label:'English Mastiff'},
    {label:'English Setter'},
    {label:'English Shepherd'},
    {label:'English Springer Spaniel'},
    {label:'English Toy Spaniel'},
    {label:'Entlebucher Mountain Dog'},
    {label:'Eskipoo'},
    {label:'Eurasier'},
    {label:'Faux Frenchbo Bulldog'},
    {label:'Field Spaniel'},
    {label:'Finnish Lapphund'},
    {label:'Finnish Spitz'},
    {label:'Flat-Coated Retriever'},
    {label:'Formosan Mountain Dog'},
    {label:'French Bulldog'},
    {label:'French Chihuahua'},
    {label:'Galgo Español'},
    {label:'German Pinscher'},
    {label:'German Shephard'},
    {label:'German Shorthaired Pointer'},
    {label:'German Spitz'},
    {label:'German Wirehaired Pointer'},
    {label:'Giant Schnauzer'},
    {label:'Glen of Imaal Terrier'},
    {label:'Goldador'},
    {label:'Goldendoodle'},
    {label:'Gordon Setter'},
    {label:'Grand Basset Griffon Vendéen'},
    {label:'Great Dane'},
    {label:'Great Pyrenees'},
    {label:'Greater Swiss Mountain Dog'},
    {label:'Greybull'},
    {label:'Greyhound'},
    {label:'Griffon Korthal'},
    {label:'Harrier'},
    {label:'Havachon'},
    {label:'Havanese'},
    {label:'Havatese'},
    {label:'Hokkaido Ken'},
    {label:'Icelandic Sheepdog'},
    {label:'Insane Chicken Dog'},
    {label:'Irish Red and White Setter'},
    {label:'Irish Setter'},
    {label:'Irish Terrier'},
    {label:'Irish Water Spaniel'},
    {label:'Irish Wolfhound'},
    {label:'Italian Greyhound'},
    {label:'Jack Chi'},
    {label:'Jack Russell Terrier'},
    {label:'Jack-A-Bee'},
    {label:'Jackapoo'},
    {label:'JackWeenie'},
    {label:'Japanese Akita'},
    {label:'Japanese Chin'},
    {label:'Japanese Spitz'},
    {label:'Jug'},
    {label:'Kai Ken'},
    {label:'Keeshond'},
    {label:'Kerry Blue Terrier'},
    {label:'Kishu Ken'},
    {label:'Komondor'},
    {label:'Korean Jindo'},
    {label:'Kuvasz'},
    {label:'La-Chon'},
    {label:'Labradoodle'},
    {label:'Lacy'},
    {label:'Lagotto Romagnolo'},
    {label:'Lakeland Terrier'},
    {label:'Leonberger'},
    {label:'Lhasa Apso'},
    {label:'Lhasapoo'},
    {label:'Lowchen'},
    {label:'Maltese'},
    {label:'Maltichon'},
    {label:'Maltipoo'},
    {label:'Maltzu'},
    {label:'Manchester Terrier'},
    {label:'Maremma Sheepdog'},
    {label:'Marvelous Mystery Mutt'},
    {label:'Mastador'},
    {label:'Mastiff'},
    {label:'Mini Bernedoodle'},
    {label:'Miniature American Shepherd'},
    {label:'Miniature Australian Shepherd'},
    {label:'Miniature Bull Terrier'},
    {label:'Miniature Dachshund'},
    {label:'Miniature Pinscher'},
    {label:'Miniature Poodle'},
    {label:'Miniature Schnauzer'},
    {label:'Morkie'},
    {label:'Muggin'},
    {label:'Neapolitan Mastiff'},
    {label:'New Zealand Huntaway'},
    {label:'Newfoundland'},
    {label:'Norfolk Terrier'},
    {label:'Northern Inuit'},
    {label:'Norwegian Buhund'},
    {label:'Norwegian Elkhound'},
    {label:'Norwegian Lundehund'},
    {label:'Norwich Terrier'},
    {label:'Nova Scotia Duck Tolling Retriever'},
    {label:'Old English Sheepdog'},
    {label:'Olde English Bulldogge'},
    {label:'Ori Pei'},
    {label:'Otterhound'},
    {label:'Papichon'},
    {label:'Papillon'},
    {label:'Parson Russell Terrier'},
    {label:'Patterdale Terrier'},
    {label:'Peek-a-Pom'},
    {label:'Peekapoo'},
    {label:'Pekingese'},
    {label:'Petit Basset Griffon Vendeen'},
    {label:'Pharaoh Hound'},
    {label:'Plott'},
    {label:'Pointer'},
    {label:'Polish Lowland Sheepdog'},
    {label:'Pom Chi'},
    {label:'Pomapoo'},
    {label:'Pomeranian'},
    {label:'Pomino'},
    {label:'Poodle'},
    {label:'Poogle'},
    {label:'Portuguese Podengo Pequeno'},
    {label:'Portuguese Water Dog'},
    {label:'Prague Ratter'},
    {label:'Presa Canario'},
    {label:'Pug'},
    {label:'Pugapoo'},
    {label:'Puggle'},
    {label:'Pugshire'},
    {label:'Puli'},
    {label:'Pumi'},
    {label:'Pyrenean Shepherd'},
    {label:'Rat Terrier'},
    {label:'Ratonero Bodeguero Andaluz'},
    {label:'Redbone Coonhound'},
    {label:'Rhodesian Ridgeback'},
    {label:'Rottweiler'},
    {label:'Russell Terrier'},
    {label:'Saint Berdoodle'},
    {label:'Saluki'},
    {label:'Samoyed'},
    {label:'Samusky'},
    {label:'Schipperke'},
    {label:'Schipperpoo'},
    {label:'Schnoodle'},
    {label:'Schweenie'},
    {label:'Scotchie'},
    {label:'Scottish Deerhound'},
    {label:'Scottish Terrier'},
    {label:'Sealyham Terrier'},
    {label:'Shar-Poo'},
    {label:'Sheltiedoodle'},
    {label:'Shetland Sheepdog'},
    {label:'Shichon'},
    {label:'Shih Tzu'},
    {label:'Shih-poo'},
    {label:'Shikoku Ken'},
    {label:'Shiloh Shepherd'},
    {label:'Shinese'},
    {label:'Shiranian'},
    {label:'Shorkie Tzu'},
    {label:'Siberian Husky'},
    {label:'Silken Windhound'},
    {label:'Silkshire Terrier'},
    {label:'Silky Terrier'},
    {label:'Skye Terrier'},
    {label:'Sloughi'},
    {label:'Smooth Collie'},
    {label:'Smooth Fox Terrier'},
    {label:'Snorkie'},
    {label:'Soft Coated Wheaten Terrier'},
    {label:'Spanish Water Dog'},
    {label:'Spinone Italiano'},
    {label:'St. Bernard'},
    {label:'Staffordshire Bull Boxer'},
    {label:'Staffordshire Bull Terrier'},
    {label:'Standard Poodle'},
    {label:'Standard Schnauzer'},
    {label:'Super Rare'},
    {label:'Sussex Spaniel'},
    {label:'Swedish Vallhund'},
    {label:'Tamaskan'},
    {label:'Tibalier'},
    {label:'Tibetan Mastiff'},
    {label:'Tibetan Spaniel'},
    {label:'Tibetan Terrier'},
    {label:'Toy Fox Terrier'},
    {label:'Toy Poodle'},
    {label:'Treeing Walker Coonhound'},
    {label:'Valley Bulldog'},
    {label:'Vizsla'},
    {label:'Weimaraner'},
    {label:'Welsh Springer Spaniel'},
    {label:'Welsh Terrier'},
    {label:'West Highland White Terrier'},
    {label:'Westiepoo'},
    {label:'Westion'},
    {label:'Whippet'},
    {label:'White Shepherd'},
    {label:'Whoodle'},
    {label:'Wire Fox Terrier'},
    {label:'Wirehaired Pointing Griffon'},
    {label:'Wirehaired Vizsla'},
    {label:'Xoloitzcuintli'},
    {label:'Yo-Chon'},
    {label:'Yorkie Pom'},
    {label:'Yorkiepoo'},
    {label:'Yorkshire Terrier'}
]
